import { FLOORING_IMAGES, IMAGE_ALT_TEXT } from './images';

export const FLOORING_SERVICES = [
  {
    id: 'hardwood',
    name: 'Hardwood Flooring',
    slug: 'hardwood-flooring-installation',
    icon: 'trees',
    description: 'Premium hardwood flooring installation with expert craftsmanship and lasting beauty.',
    shortDesc: 'Timeless elegance and natural beauty',
    benefits: [
      'Increases home value significantly',
      'Durable and long-lasting (25+ years)',
      'Easy to clean and maintain',
      'Available in various wood species and finishes',
      'Can be refinished multiple times',
    ],
    image: FLOORING_IMAGES.hardwood.thumbnail,
    bannerImage: FLOORING_IMAGES.hardwood.banner,
    imageAlt: IMAGE_ALT_TEXT.hardwood,
  },
  {
    id: 'laminate',
    name: 'Laminate Flooring',
    slug: 'laminate-flooring-installation',
    icon: 'layers',
    description: 'Affordable laminate flooring that mimics hardwood with easy maintenance and durability.',
    shortDesc: 'Budget-friendly wood-look flooring',
    benefits: [
      'Scratch and stain resistant',
      'Easy to install and maintain',
      'Wide variety of styles and colors',
      'Durable and reliable performance',
      'Environmentally friendly options available',
    ],
    image: FLOORING_IMAGES.laminate.thumbnail,
    bannerImage: FLOORING_IMAGES.laminate.banner,
    imageAlt: IMAGE_ALT_TEXT.laminate,
  },
  {
    id: 'vinyl',
    name: 'Vinyl Flooring',
    slug: 'vinyl-flooring-installation',
    icon: 'square',
    description: 'Waterproof vinyl flooring perfect for kitchens, bathrooms, and basements.',
    shortDesc: '100% waterproof and versatile',
    benefits: [
      'Completely waterproof and moisture resistant',
      'Ideal for basements and bathrooms',
      'Soft underfoot and comfortable',
      'Available in luxury vinyl plank (LVP) and tile (LVT)',
      'Easy to clean and maintain',
    ],
    image: FLOORING_IMAGES.vinyl.thumbnail,
    bannerImage: FLOORING_IMAGES.vinyl.banner,
    imageAlt: IMAGE_ALT_TEXT.vinyl,
  },
  {
    id: 'tile',
    name: 'Tile Flooring',
    slug: 'tile-flooring-installation',
    icon: 'grid',
    description: 'Professional tile installation for kitchens, bathrooms, and high-traffic areas.',
    shortDesc: 'Durable and water-resistant',
    benefits: [
      'Extremely durable and long-lasting',
      'Water resistant perfect for wet areas',
      'Easy to clean and hygienic',
      'Heat resistant ideal for radiant heating',
      'Endless design possibilities',
    ],
    image: FLOORING_IMAGES.tile.thumbnail,
    bannerImage: FLOORING_IMAGES.tile.banner,
    imageAlt: IMAGE_ALT_TEXT.tile,
  },
  {
    id: 'carpet',
    name: 'Carpet Installation',
    slug: 'carpet-installation',
    icon: 'wind',
    description: 'Comfortable carpet installation for bedrooms, living rooms, and offices.',
    shortDesc: 'Soft, warm, and comfortable',
    benefits: [
      'Soft and comfortable underfoot',
      'Excellent sound absorption',
      'Provides insulation and warmth',
      'Wide range of colors and textures',
      'Versatile for many room types',
    ],
    image: FLOORING_IMAGES.carpet.thumbnail,
    bannerImage: FLOORING_IMAGES.carpet.banner,
    imageAlt: IMAGE_ALT_TEXT.carpet,
  },
];

export const FLOORING_TYPES = FLOORING_SERVICES.map(service => ({
  value: service.id,
  label: service.name,
}));
